name: env
description: Construct env for each operating system
runs:
  using: 'composite'
  steps:
    - shell: bash
      run: |
        cat >> $GITHUB_ENV << EOF
        XDIST_ARGUMENTS=-n auto
        PYTEST_ARGUMENTS=--randomly-seed=1 --disable-warnings --reruns 1 --reruns-delay 1 --verbose --durations=3 --showlocals
        EOF

    - shell: bash
      run: |
        cat >> $GITHUB_ENV << EOF
        PYTEST_CORE_ARGUMENTS=./src/tribler/core ${PYTEST_ARGUMENTS}
        PYTEST_TUNNELS_ARGUMENTS=./src/tribler/core/components/tunnel/tests/test_full_session --tunneltests ${PYTEST_ARGUMENTS}
        PYTEST_GUI_ARGUMENTS=./src/tribler/gui --guitests ${PYTEST_ARGUMENTS}
        EOF

    - if: runner.os == 'Linux'  ||  runner.os == 'macOS'
      shell: bash
      run: |
        cat >> $GITHUB_ENV << EOF
        PYTEST_CORE_ARGUMENTS=${PYTEST_CORE_ARGUMENTS} --looptime
        PYTEST_TUNNELS_ARGUMENTS=${PYTEST_TUNNELS_ARGUMENTS} --looptime
        PYTEST_GUI_ARGUMENTS=${PYTEST_GUI_ARGUMENTS} --looptime
        EOF

    - if: runner.os == 'Linux'
      shell: bash
      run: |
        cat >> $GITHUB_ENV << EOF
        XDIST_ARGUMENTS=--tx '2*popen//execmodel=eventlet'
        EOF
