#!/bin/sh -x
#
# We should run the tests in a separate Python interpreter to prevent
# problems with our singleton classes, e.g. SuperPeerDB, etc.
#
# WARNING: this shell script must use \n as end-of-line, Windows
# \r\n gives problems running this on Linux

PYTHONPATH=../..:"$PYTHONPATH"
export PYTHONPATH

python test_sqlitecachedbhandler.py TestSqliteBasicDBHandler singtest_size
python test_sqlitecachedbhandler.py TestSqliteBasicDBHandler singtest_getOne
python test_sqlitecachedbhandler.py TestSqliteBasicDBHandler singtest_getAll

python test_sqlitecachedbhandler.py TestSqliteMyDBHandler singtest_get
python test_sqlitecachedbhandler.py TestSqliteMyDBHandler singtest_put

python test_sqlitecachedbhandler.py TestSuperPeerDBHandler singtest_setSuperPeer
python test_sqlitecachedbhandler.py TestSuperPeerDBHandler singtest_addExternalSuperPeer

python test_sqlitecachedbhandler.py TestFriendDBHandler singtest_size
python test_sqlitecachedbhandler.py TestFriendDBHandler singtest_getFriends
python test_sqlitecachedbhandler.py TestFriendDBHandler singtest_setFriendState
python test_sqlitecachedbhandler.py TestFriendDBHandler singtest_addExternalFriend

python test_sqlitecachedbhandler.py TestSqlitePeerDBHandler singtest_getList
python test_sqlitecachedbhandler.py TestSqlitePeerDBHandler singtest_getPeerSim
python test_sqlitecachedbhandler.py TestSqlitePeerDBHandler singtest_getPeerList
python test_sqlitecachedbhandler.py TestSqlitePeerDBHandler singtest_getPeers
python test_sqlitecachedbhandler.py TestSqlitePeerDBHandler singtest_addPeer
python test_sqlitecachedbhandler.py TestSqlitePeerDBHandler singtest_aa_hasPeer
python test_sqlitecachedbhandler.py TestSqlitePeerDBHandler singtest_findPeers
python test_sqlitecachedbhandler.py TestSqlitePeerDBHandler singtest_updatePeer
python test_sqlitecachedbhandler.py TestSqlitePeerDBHandler singtest_deletePeer
python test_sqlitecachedbhandler.py TestSqlitePeerDBHandler singtest_updatePeer
python test_sqlitecachedbhandler.py TestSqlitePeerDBHandler singtest_getPermIDByIP
python test_sqlitecachedbhandler.py TestSqlitePeerDBHandler singtest_loadPeers

python test_sqlitecachedbhandler.py TestPreferenceDBHandler singtest_getPrefList
python test_sqlitecachedbhandler.py TestPreferenceDBHandler singtest_addPreference
python test_sqlitecachedbhandler.py TestPreferenceDBHandler singtest_addPeerPreferences

python test_sqlitecachedbhandler.py TestTorrentDBHandler singtested_functions
python test_sqlitecachedbhandler.py TestTorrentDBHandler singtest_count
python test_sqlitecachedbhandler.py TestTorrentDBHandler singtest_loadTorrents
python test_sqlitecachedbhandler.py TestTorrentDBHandler singtest_add_update_delete_Torrent
python test_sqlitecachedbhandler.py TestTorrentDBHandler singtest_getCollectedTorrentHashes
python test_sqlitecachedbhandler.py TestTorrentDBHandler singtest_freeSpace

python test_sqlitecachedbhandler.py TestMyPreferenceDBHandler singtest_getPrefList
python test_sqlitecachedbhandler.py TestMyPreferenceDBHandler singtest_getCreationTime
python test_sqlitecachedbhandler.py TestMyPreferenceDBHandler singtest_getRecentLivePrefList
python test_sqlitecachedbhandler.py TestMyPreferenceDBHandler singtest_hasMyPreference
python test_sqlitecachedbhandler.py TestMyPreferenceDBHandler singtest_addMyPreference_deletePreference
python test_sqlitecachedbhandler.py TestMyPreferenceDBHandler singtest_updateProgress
python test_sqlitecachedbhandler.py TestMyPreferenceDBHandler singtest_getMyPrefListInfohash
python test_sqlitecachedbhandler.py TestMyPreferenceDBHandler singtest_getMyPrefStats
