component_depth: 1
languages:
- javascript
- python
- script
exclude:
- /Tribler/Core/APIImplementation/.*
- /Tribler/Core/CacheDB/.*
- /Tribler/Core/Category/.*
- /Tribler/Core/Config/.*
- /Tribler/Core/CreditMining/.*
- /Tribler/Core/DecentralizedTracking/.*
- /Tribler/Core/DownloadConfig.py
- /Tribler/Core/DownloadState.py
- /Tribler/Core/Libtorrent/.*
- /Tribler/Core/Modules/__init__.py
- /Tribler/Core/Modules/channel/.*
- /Tribler/Core/Modules/process_checker.py
- /Tribler/Core/Modules/restapi/__init__.py
- /Tribler/Core/Modules/restapi/channels/.*
- /Tribler/Core/Modules/restapi/create_torrent_endpoint.py
- /Tribler/Core/Modules/restapi/debug_endpoint.py
- /Tribler/Core/Modules/restapi/downloads_endpoint.py
- /Tribler/Core/Modules/restapi/events_endpoint.py
- /Tribler/Core/Modules/restapi/multichain_endpoint.py
- /Tribler/Core/Modules/restapi/rest_manager.py
- /Tribler/Core/Modules/restapi/root_endpoint.py
- /Tribler/Core/Modules/restapi/search_endpoint.py
- /Tribler/Core/Modules/restapi/settings_endpoint.py
- /Tribler/Core/Modules/restapi/shutdown_endpoint.py
- /Tribler/Core/Modules/restapi/state_endpoint.py
- /Tribler/Core/Modules/restapi/statistics_endpoint.py
- /Tribler/Core/Modules/restapi/torrentinfo_endpoint.py
- /Tribler/Core/Modules/restapi/torrents_endpoint.py
- /Tribler/Core/Modules/restapi/util.py
- /Tribler/Core/Modules/restapi/variables_endpoint.py
- /Tribler/Core/Modules/search_manager.py
- /Tribler/Core/Modules/tracker_manager.py
- /Tribler/Core/Modules/versioncheck_manager.py
- /Tribler/Core/Modules/watch_folder.py
- /Tribler/Core/RemoteTorrentHandler.py
- /Tribler/Core/Session.py
- /Tribler/Core/SessionConfig.py
- /Tribler/Core/TFTP/.*
- /Tribler/Core/TorrentChecker/.*
- /Tribler/Core/TorrentDef.py
- /Tribler/Core/Upgrade/.*
- /Tribler/Core/Utilities/.*
- /Tribler/Core/Video/.*
- /Tribler/Core/__init__.py
- /Tribler/Core/defaults.py
- /Tribler/Core/exceptions.py
- /Tribler/Core/leveldbstore.py
- /Tribler/Core/osutils.py
- /Tribler/Core/permid.py
- /Tribler/Core/plyveladapter.py
- /Tribler/Core/simpledefs.py
- /Tribler/Core/statistics.py
- /Tribler/Core/version.py
- /Tribler/Main/.*
- /Tribler/__init__.py
- /Tribler/community/__init__.py
- /Tribler/community/allchannel/.*
- /Tribler/community/channel/.*
- /Tribler/community/multichain/__init__.py
- /Tribler/community/multichain/block.py
- /Tribler/community/multichain/conversion.py
- /Tribler/community/multichain/database.py
- /Tribler/community/multichain/payload.py
- /Tribler/community/search/.*
- /Tribler/community/tunnel/.*
- /TriblerGUI/__init__.py
- /TriblerGUI/core_manager.py
- /TriblerGUI/debug_window.py
- /TriblerGUI/defs.py
- /TriblerGUI/dialogs/.*
- /TriblerGUI/event_request_manager.py
- /TriblerGUI/scripts/.*
- /TriblerGUI/single_application.py
- /TriblerGUI/tribler_action_menu.py
- /TriblerGUI/tribler_app.py
- /TriblerGUI/tribler_request_manager.py
- /TriblerGUI/utilities.py
- /TriblerGUI/vlc.py
- /TriblerGUI/widgets/__init__.py
- /TriblerGUI/widgets/channel_list_item.py
- /TriblerGUI/widgets/channel_torrent_list_item.py
- /TriblerGUI/widgets/channelpage.py
- /TriblerGUI/widgets/circlebutton.py
- /TriblerGUI/widgets/createtorrentpage.py
- /TriblerGUI/widgets/discoveredpage.py
- /TriblerGUI/widgets/discoveringpage.py
- /TriblerGUI/widgets/downloadfilewidgetitem.py
- /TriblerGUI/widgets/downloadprogressbar.py
- /TriblerGUI/widgets/downloadsdetailstabwidget.py
- /TriblerGUI/widgets/downloadspage.py
- /TriblerGUI/widgets/downloadwidgetitem.py
- /TriblerGUI/widgets/editchannelpage.py
- /TriblerGUI/widgets/ellipsebutton.py
- /TriblerGUI/widgets/home_recommended_item.py
- /TriblerGUI/widgets/homepage.py
- /TriblerGUI/widgets/lazyloadlist.py
- /TriblerGUI/widgets/leftmenuplaylist.py
- /TriblerGUI/widgets/loading_list_item.py
- /TriblerGUI/widgets/loadingpage.py
- /TriblerGUI/widgets/manageplaylistpage.py
- /TriblerGUI/widgets/playlist_list_item.py
- /TriblerGUI/widgets/playlistpage.py
- /TriblerGUI/widgets/searchresultspage.py
- /TriblerGUI/widgets/settingspage.py
- /TriblerGUI/widgets/subscribedchannelspage.py
- /TriblerGUI/widgets/subscriptionswidget.py
- /TriblerGUI/widgets/tabbuttonpanel.py
- /TriblerGUI/widgets/text_list_item.py
- /TriblerGUI/widgets/thumbnailwidget.py
- /TriblerGUI/widgets/underlinetabbutton.py
- /TriblerGUI/widgets/videoplayerinfobutton.py
- /TriblerGUI/widgets/videoplayerinfopopup.py
- /TriblerGUI/widgets/videoplayerpage.py
- /TriblerGUI/widgets/videoplayerpositionslider.py
- /TriblerGUI/widgets/videoplayervolumecontainer.py
- /TriblerGUI/widgets/videoplayerwidget.py
- /doc/conf.py
- /mac/makedistmac_64bit.sh
- /run_tribler.py
- /setup.py
- /tribler.sh
- /twisted/plugins/.*
- /win/locate-python.py

