#https://docs.codeclimate.com/docs/advanced-configuration#section-configuration-file-structure-and-content

version: "2"

plugins:
  pylint: # this plugin uses .pylintrc as a config file
    enabled: true
    PYTHONPATH:
      - ./src
  bandit:
    enabled: true
  sonar-python:
    enabled: true
