#https://docs.codeclimate.com/docs/advanced-configuration#section-configuration-file-structure-and-content

version: "2"

plugins:
  pep8: # this plugin uses `tox.ini` as a config file
    enabled: true
  bandit:
    enabled: true
  sonar-python:
    enabled: true
