# https://docs.codeclimate.com/docs/advanced-configuration
version: "2"

plugins:
  pylint: # it uses .pylintrc as a config file
    enabled: true
  bandit:
    enabled: true
  sonar-python:
    enabled: true
