#!/bin/sh

source /etc/bashrc

module load python/2.6.6
module load prun

#echo $SGE_TASK_ID $SGE_TASK_FIRST $SGE_TASK_LAST $SGE_TASK_STEPSIZE

if test $# -ne 4; then
	echo "Usage: $0 <experiment-config> <peers-directory> <peer-count> <experiment-length-in-min>"
	exit 1
fi

EXPERIMENT_CONFIG=$1
source $EXPERIMENT_CONFIG # we get $BRANCH from the config file

PEERS_DIRECTORY=$2
cd $PEERS_DIRECTORY
PEERS_DIRECTORY=$(pwd)

PEER_COUNT=$3
EXPERIMENT_LENGTH=$4
PEERS_PER_NODE=$[ $PEER_COUNT / $SGE_TASK_LAST ]

# Clean output of previous runs
rm -rf $PEERS_DIRECTORY/control/$(hostname)
mkdir -p $PEERS_DIRECTORY/control/$(hostname)
mkdir -p $PEERS_DIRECTORY/control/$(hostname)/output/

netstat -su  > $PEERS_DIRECTORY/control/$(hostname)/output/udp_stats_start.txt

# clean temporary directory
rm -rf /tmp/mbardac/dispersy/
mkdir -p /tmp/mbardac/dispersy/

let STARTING_TIMESTAMP=`date +%s`+120

for i in $(seq 1 1 $PEERS_PER_NODE); do
	echo "cd ${BRANCH}; ./barter-peer-run $PEERS_DIRECTORY starting_timestamp=$STARTING_TIMESTAMP,timestep=20.0" >> $PEERS_DIRECTORY/control/$(hostname)/start_commands
done

export PYTHONPATH=${BRANCH}
${BRANCH}/process_guard.py \
	$PEERS_DIRECTORY/control/$(hostname)/start_commands \
	$PEERS_DIRECTORY/control/$(hostname)/output/ \
	$EXPERIMENT_LENGTH

# save the output of the run for all peers on this node
# take the output from the temporary directory
cd /tmp/mbardac/dispersy

find . -maxdepth 1 -mindepth 1 -type d | while read PEER_DIR; do 
	# we have the peer directory in PEER_DIR
	PEER_ID=$(echo $PEER_DIR | cut -c3-7)
	mkdir -p $PEERS_DIRECTORY/$PEER_ID/output
	find $PEER_DIR -type f ! -name 'bartercast.log' ! -name 'availability.log' ! -name 'peer-keys' ! -name 'peer*' -exec cp {} $PEERS_DIRECTORY/$PEER_ID/output/ \;
done

# remove temporary directory
rm -rf /tmp/mbardac/

netstat -su  > $PEERS_DIRECTORY/control/$(hostname)/output/udp_stats_stop.txt

exit 0

