#!/bin/bash
# Mircea Bardac, 2011

if test $# -ne 2; then
    echo "Error: $0 <peers-directory> <output-zip-file>"
    exit 1
fi

CWD=$(pwd)
PEERS_DIRECTORY=$1
OUTPUT_FILE=$2
OUTPUT_FILE_BASE=$(basename $OUTPUT_FILE)
OUTPUT_DIRECTORY_BASE=$(basename $OUTPUT_FILE | sed 's/\(.*\)\..*/\1/g')
OUTPUT_DIRECTORY=/tmp/$USER/$OUTPUT_DIRECTORY_BASE

rm -rf $OUTPUT_DIRECTORY
mkdir -p $OUTPUT_DIRECTORY

cd $PEERS_DIRECTORY
find . ! -wholename './control*' -and ! -name '*.db*' -and ! -wholename './*/data*' -and ! -name '*.conf' -print0 | rsync -avz --files-from=- -0  . $OUTPUT_DIRECTORY/

cd $OUTPUT_DIRECTORY/..
zip -r $OUTPUT_FILE_BASE $OUTPUT_DIRECTORY_BASE

cd $CWD
mv $OUTPUT_DIRECTORY/../$OUTPUT_FILE_BASE $OUTPUT_FILE

rm -rf $OUTPUT_DIRECTORY

ls -lh $OUTPUT_FILE

