# Written by Arno Bakker
# see LICENSE.txt for license information

# See ABCStatusBar 
ACT_NONE = 0
ACT_UPNP = 1
ACT_REACHABLE = 2
ACT_GET_EXT_IP_FROM_PEERS = 3
ACT_MEET = 4
ACT_GOT_METADATA = 5
ACT_RECOMMEND = 6
ACT_DISK_FULL = 7
ACT_NEW_VERSION = 8
