import sys

# fonts
if sys.platform == 'darwin': # mac os x
    FONT_SIZE_SR_MSG=11
    FONT_SIZE_TOTAL_DOWN=9
    FONT_SIZE_TOTAL_UP=9
    FONT_SIZE_PAGE=10
    FONT_SIZE_PAGE_OVER=11
    FONT_SIZE_FAMILY_FILTER=10
    FONT_SIZE_FILES_FRIENDS=11
    FONT_SIZE_SHARING_REPUTATION=11
    FONT_SIZE_SEARCH_RESULTS=12
    FONT_SIZE_SEARCH=14
    FONT_SIZE_SEARCH_CHOICE=9

elif sys.platform == 'win32': # windows

    FONT_SIZE_SR_MSG=8
    FONT_SIZE_TOTAL_DOWN=7
    FONT_SIZE_TOTAL_UP=7
    FONT_SIZE_PAGE=8
    FONT_SIZE_PAGE_OVER=9
    FONT_SIZE_FAMILY_FILTER=8
    FONT_SIZE_FILES_FRIENDS=8
    FONT_SIZE_SHARING_REPUTATION=8
    FONT_SIZE_SEARCH_RESULTS=8
    FONT_SIZE_SEARCH=10
    FONT_SIZE_SEARCH_CHOICE=7

else: # linux

    FONT_SIZE_SR_MSG=8
    FONT_SIZE_TOTAL_DOWN=7
    FONT_SIZE_TOTAL_UP=7
    FONT_SIZE_PAGE=8
    FONT_SIZE_PAGE_OVER=10
    FONT_SIZE_FAMILY_FILTER=8
    FONT_SIZE_FILES_FRIENDS=8
    FONT_SIZE_SHARING_REPUTATION=8
    FONT_SIZE_SEARCH_RESULTS=8
    FONT_SIZE_SEARCH=10
    FONT_SIZE_SEARCH_CHOICE=7
