# generated by wx.Glade 0.6.3 on Thu Feb 05 15:42:50 2009
# 
# Arno: please edit TopSearchPanel.xrc in some XRC editor, then generate
# code for it using wxGlade (single python file mode), and copy the
# relevant parts from it into this file, see "MAINLY GENERATED" line below.
#
# We need this procedure as there is a bug in wxPython 2.8.x on Win32 that
# cause the painting/fitting of the panel to fail. All elements wind up in
# the topleft corner. This is a wx bug as it also happens in XRCED when you
# display the panel twice.
#

import wx.animate
from GuiUtility import GUIUtility
from Tribler.Main.Utility.utility import Utility
from Tribler.__init__ import LIBRARYNAME
from Tribler.Core.CacheDB.SqliteCacheDBHandler import UserEventLogDBHandler, NetworkBuzzDBHandler
from Tribler.Core.simpledefs import NTFY_TERM
from Tribler.Core.APIImplementation.miscutils import NamedTimer
from Tribler.Core.Session import Session

from bgPanel import bgPanel
from tribler_topButton import *
from traceback import print_exc

DEBUG = False

class TopSearchPanel(bgPanel):
    def __init__(self, *args, **kwds):
        if DEBUG:
            print >> sys.stderr , "TopSearchPanel: __init__"
        bgPanel.__init__(self, *args, **kwds)
        self.init_ready = False
        self.guiUtility = GUIUtility.getInstance()
        self.utility = self.guiUtility.utility 
        self.installdir = self.utility.getPath()
        self.animationTimer = None
        
        self.buttonsBackgroundColourSelected = wx.Colour(235, 233, 228)
        self.buttonsBackgroundColour = wx.Colour(193, 188, 177)
        self.buttonsForegroundColour = wx.BLACK
        
        self.uelog = UserEventLogDBHandler.getInstance()
        self.nbdb = NetworkBuzzDBHandler.getInstance()
    
    def OnAutoComplete(self):
        self.OnSearchKeyDown()
        self.uelog.addEvent(message="TopSearchPanel: user used autocomplete", type = 2)  
    
    def OnSearchKeyDown(self, event = None):
        if DEBUG:
            print >> sys.stderr, "TopSearchPanel: OnSearchKeyDown"
        wx.CallAfter(self.guiUtility.dosearch)
    
    def StartSearch(self):
        self.ag.Show()
        self.go.GetContainingSizer().Layout()
        self.ag.Play()
            
        # Timer to stop animation after 10 seconds. No results will come 
        # in after that
        if self.animationTimer:
            self.animationTimer.Restart(10000)
        else:
            self.animationTimer = wx.CallLater(10000, self.HideAnimation)
            
        if not self.results.IsEnabled():
            self.results.Enable()
                  
        self.selectTab('search_results')
        self.results.SetValue(True)
    
    def OnResults(self, event):
        self._selectPage('search_results')

    def OnChannels(self, event):
        if self.guiUtility.guiPage not in ['channels', 'mychannel']:
            wx.CallAfter(self.guiUtility.ShowPage, 'channels')
        self.selectTab('channels')
   
    def OnSettings(self, event):
        self._selectPage('settings')
    
    def OnHome(self, event):
        self._selectPage('home')
        
    def OnLibrary(self, event):
        self._selectPage('my_files')
    
    def OnStats(self, event):
        self._selectPage('stats')
    
    def _selectPage(self, page):
        if self.guiUtility.guiPage != page:
            wx.CallAfter(self.guiUtility.ShowPage, page)
            
        self.selectTab(page)
        
    def selectTab(self, tab):
        self.home.SetValue(tab == 'home')
        self.results.SetValue(tab == 'search_results')
        self.channels.SetValue(tab == 'channels')
        self.settings.SetValue(tab == 'settings')
        self.my_files.SetValue(tab == 'my_files')
                
    def complete(self, term):
        """autocompletes term."""
        if len(term) > 1:
            return self.nbdb.getTermsStartingWith(term, num=7)
        return []

    def SearchFocus(self):
        self.searchField.SetFocus()
        self.searchField.SelectAll()

    def Bitmap(self, path, type):
        namelist = path.split("/")
        path = os.path.join(self.installdir, LIBRARYNAME, "Main", "vwxGUI", *namelist)
        return wx.Bitmap(path, type)
        
    def _PostInit(self):
        if DEBUG:
            print >> sys.stderr, "TopSearchPanel: OnCreate"
        
        bgPanel._PostInit(self)
        self.SetBackgroundColour(wx.Colour(255, 255, 255))
        
        
        """
        if sys.platform == 'linux2':
            #bug in linux for searchctrl, focus does not hide search text + text stays grey
            self.searchField = wx.TextCtrl(self, -1, "", style=wx.TE_PROCESS_ENTER)
        else:
            self.searchField = wx.SearchCtrl(self, -1, "", style=wx.TE_PROCESS_ENTER)
        self.searchField.SetMinSize((400, -1))
        self.searchField.SetFocus()
        
        self.searchField.Bind(wx.EVT_SEARCHCTRL_SEARCH_BTN, self.OnSearchKeyDown)
        """
        
        if sys.platform == 'darwin':
            self.searchField = wx.SearchCtrl(self, -1, "", style=wx.TE_PROCESS_ENTER)
            self.searchField.Bind(wx.EVT_SEARCHCTRL_SEARCH_BTN, self.OnSearchKeyDown)
        else:
            self.searchField = TextCtrlAutoComplete(self, entrycallback = self.complete, selectcallback = self.OnAutoComplete)
        self.searchField.SetMinSize((400, -1))
        self.searchField.SetFocus()
        self.searchField.Bind(wx.EVT_TEXT_ENTER, self.OnSearchKeyDown)
        
        self.go = tribler_topButton(self,-1,name = 'Search_new')
        self.go.SetMinSize((50, 24))
        self.go.Bind(wx.EVT_LEFT_UP, self.OnSearchKeyDown)
        
        def createToggle(label, event):
            button = wx.ToggleButton(self, -1, label)
            button.Bind(wx.EVT_TOGGLEBUTTON, event)
            return button
        
        self.channels = createToggle('Channels', self.OnChannels)
        self.settings = createToggle('Settings', self.OnSettings)
        self.my_files = createToggle('Library', self.OnLibrary)
        self.results = createToggle('Results', self.OnResults)
        self.results.Disable()
        
        self.home = createToggle('Home', self.OnHome)
        self.selectTab('home')
        
        if sys.platform == 'win32':
            self.files_friends = wx.StaticBitmap(self, -1, self.Bitmap("images/search_files_channels.png", wx.BITMAP_TYPE_ANY))
            self.tribler_logo2 = wx.StaticBitmap(self, -1, self.Bitmap("images/logo4video2_win.png", wx.BITMAP_TYPE_ANY))
        else:    
            self.files_friends = wx.StaticText(self, -1, "Search Files or Channels") 
            self.tribler_logo2 = wx.StaticBitmap(self, -1, self.Bitmap("images/logo4video2.png", wx.BITMAP_TYPE_ANY))
            
            if sys.platform == 'linux2':
                self.files_friends.SetFont(wx.Font(8, wx.SWISS, wx.NORMAL, wx.BOLD, 0, "Nimbus Sans L"))
            elif sys.platform == 'darwin': # mac
                self.files_friends.SetFont(wx.Font(8, wx.SWISS, wx.NORMAL, wx.BOLD, 0, ""))
        self.tribler_logo2.Bind(wx.EVT_LEFT_UP, self.OnStats)
        
        self.__do_layout()
        self.Layout()
        
        self.init_ready = True
        self.Bind(wx.EVT_SIZE, self.OnResize)
        
    def __do_layout(self):
        mainSizer = wx.BoxSizer(wx.HORIZONTAL)
        
        #Add searchbox etc.
        searchSizer = wx.BoxSizer(wx.VERTICAL)

        #Search for files or channels label
        searchSizer.Add(self.files_friends, 0, wx.TOP, 20) 
        if sys.platform == 'win32': #platform specific spacer
            searchSizer.AddSpacer((0, 6))
        else:
            searchSizer.AddSpacer((0, 3))
        
        searchBoxSizer = wx.BoxSizer(wx.HORIZONTAL)
        searchBoxSizer.Add(self.searchField, 1, wx.TOP, 1) #add searchbox
        searchBoxSizer.Add(self.go, 0, wx.ALIGN_CENTER_VERTICAL | wx.LEFT, 5) #add searchbutton

        if sys.platform == 'darwin' or sys.platform == 'win32':
            ag_fname = os.path.join(self.utility.getPath(), LIBRARYNAME, 'Main', 'vwxGUI', 'images', 'search_new_windows.gif')
        else:
            ag_fname = os.path.join(self.utility.getPath(), LIBRARYNAME, 'Main', 'vwxGUI', 'images', 'search_new.gif')
        self.ag = wx.animate.GIFAnimationCtrl(self, -1, ag_fname)
        self.ag.Hide()
        
        searchBoxSizer.Add(self.ag, 0, wx.ALIGN_CENTER_VERTICAL | wx.LEFT | wx.RESERVE_SPACE_EVEN_IF_HIDDEN, 3)
        searchSizer.Add(searchBoxSizer, 0, wx.EXPAND)
        
        #finished searchSizer, add to mainSizer
        mainSizer.Add(searchSizer, 0, wx.LEFT, 10)
        
        #niels: add strechingspacer, all controls added before 
        #this spacer will be aligned to the left of the screen
        #all controls added after, will be to the right
        mainSizer.AddStretchSpacer()
        
        #add buttons
        self.buttonSizer = wx.BoxSizer(wx.VERTICAL)
        
        #add buttons horizontally
        buttonBoxSizer = wx.BoxSizer(wx.HORIZONTAL)
        buttonBoxSizer.Add(self.home, 0, wx.RIGHT, 5)
        buttonBoxSizer.Add(self.results, 0, wx.RIGHT, 5)
        buttonBoxSizer.Add(self.channels, 0, wx.RIGHT, 5)
        buttonBoxSizer.Add(self.settings, 0, wx.RIGHT, 5)
        buttonBoxSizer.Add(self.my_files)
        
        self.buttonSizer.Add(buttonBoxSizer, 0, wx.TOP, 3)
        
        self.notifyPanel = wx.Panel(self)
        self.notifyPanel.SetBackgroundColour("yellow")
        self.notifyIcon = wx.StaticBitmap(self.notifyPanel, -1, wx.ArtProvider.GetBitmap(wx.ART_INFORMATION))
        self.notify = wx.StaticText(self.notifyPanel)
        
        notifyS = wx.BoxSizer(wx.HORIZONTAL)
        notifyS.Add(self.notifyIcon, 0, wx.LEFT | wx.TOP | wx.BOTTOM, 5)
        notifyS.Add(self.notify, 1, wx.LEFT | wx.RIGHT | wx.ALIGN_CENTER_VERTICAL, 5)
        self.notifyPanel.SetSizer(notifyS)
        self.notifyPanel.Hide()
        
        self.buttonSizer.Add(self.notifyPanel, 0, wx.ALIGN_RIGHT | wx.TOP, 5)
        mainSizer.Add(self.buttonSizer)
        
        mainSizer.AddSpacer((15, 0))
        
        mainSizer.Add(self.tribler_logo2, 0, wx.TOP, 3)
        mainSizer.AddSpacer((10, 0))
        self.SetSizer(mainSizer)
    
    def OnResize(self, event):
        self.Refresh()
        event.Skip()
    
    def Notify(self, msg, icon= -1):
        self.notify.SetLabel(msg)
        self.notify.SetSize(self.notify.GetBestSize())
        
        if icon != -1:
            self.notifyIcon.Show()
            self.notifyIcon.SetBitmap(wx.ArtProvider.GetBitmap(icon, wx.ART_FRAME_ICON))
        else:
            self.notifyIcon.Hide()
        
        self.Freeze()
        self.notifyPanel.Show()
        #NotifyLabel size changed, thus call Layout
        self.buttonSizer.Layout()
        self.Thaw()
        
        wx.CallLater(5000, self.HideNotify)

    def HideNotify(self):
        self.notifyPanel.Hide()
        
    def HideAnimation(self):
        self.ag.Stop()
        self.ag.Hide()
