.\" Tribler: Python based Bittorrent/Internet TV application 
.TH man 1 "12 June 2007" "1.0" "Tribler man page"
.SH NAME
tribler \- Python based Bittorrent/Internet TV application
.SH SYNOPSIS
.B tribler
.SH DESCRIPTION
.B Tribler
is a python-based Bittorrent/Internet TV application
It allows you to watch videos and download
content. Tribler aims to combine the ease of
Youtube.com with the performance of peer-to-peer.

Tribler is backwards compatible with the Bittorrent
download protocol. To discover interesting content
standard RSS feeds with .torrent links are supported
plus the "Tribe protocol" which automatically scans
the network for available Bittorrent swarms upon
startup. Tribler uses an embedded web browser to
access video clips of Youtube.com and Liveleak.com
Other features are "People who like this also like"
for recommending related swarms, the ability to
make friends, and to donate idle upload capacity
to friends. The later can improve download speed
by a factor of two on asymmetric Internet links.
The fastest way of social file sharing

Homepage: http://www.tribler.org
.SH FILES
.P 
.I /usr/bin/tribler
.I /usr/share/tribler
.SH AUTHOR
.nf
Arno Bakker (arno@cs.vu.nl)
.fi
