name: pyenv
description: Setup python and install required dependencies to venv with cache
inputs:
  python-version:
    default: '3.9'
    description: 'Python version'
    required: false

  requirements:
    default: 'requirements.txt'
    description: 'The path to requirements.txt file'
    required: false

  cache-dependency-path:
    description: 'Used to specify the path to dependency files. Supports wildcards or a list of file names for caching multiple dependencies.'
    required: false

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: ${{inputs.python-version}}
        cache: 'pip'
        cache-dependency-path: ${{inputs.cache-dependency-path}}

    - name: Install pip dependencies
      shell: bash
      run: |
        pip install -r ${{inputs.requirements}}

    - name: Print installed packages
      shell: bash
      run: |
        pip list
