name: pyenv
description: Setup python and install required dependencies to venv with cache
inputs:
  python-version:
    default: '3.8'
    description: 'Python version'
    required: false

  requirements:
    default: 'requirements.txt'
    description: 'The path to requirements.txt file'
    required: false

  requirements-key:
    default: '**/requirements*.txt'
    description: 'Requirements-files to use for building the cache key'
    required: false

  custom_cache_key_element:
    default: ${{github.ref_name}}
    description: 'Custom element that will be used when constructing the cache key'
    required: false

outputs:
  virtualenv-directory:
    description: 'The path to the restored or created virtualenv'
    value: ${{steps.cache-virtualenv.outputs.virtualenv-directory}}

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: ${{inputs.python-version}}

    - name: Restore virtual env
      uses: syphar/restore-virtualenv@v1
      id: cache-virtualenv
      with:
        requirement_files: ${{inputs.requirements-key}}
        custom_cache_key_element: ${{inputs.custom_cache_key_element}}:${{inputs.requirements}}

    - name: Install pip dependencies
      if: steps.cache-virtualenv.outputs.cache-hit != 'true'
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r ${{inputs.requirements}}

    - name: Print installed packages
      shell: bash
      run: |
        pip list
