[download_defaults]
hops = integer(default=0)
selected_files = string_list(default=list())
correctedfilename = string(default=None)
safe_seeding = boolean(default=False)
user_stopped = boolean(default=False)
share_mode = boolean(default=False)
time_added = integer(default=0)
credit_mining = boolean(default=False)
bootstrap_download = boolean(default=False)
channel_download = boolean(default=False)
add_download_to_channel = boolean(default=False)
seeding_mode = option('forever', 'never', 'ratio', 'time', default='forever')
seeding_ratio = float(default=2.0)
seeding_time = float(default=60)
saveas = string(default=None)

[state]
metainfo = string(default='ZGU=')
engineresumedata = string(default='ZGU=')
