from Tribler.dispersy.candidate import CANDIDATE_WALK_LIFETIME
MAX_CIRCUITS_TO_CREATE = 1

CIRCUIT_STATE_READY = 'READY'
CIRCUIT_STATE_CREATING = 'CREATING'
CIRCUIT_STATE_EXTENDING = 'EXTENDING'
CIRCUIT_STATE_TO_BE_EXTENDED = 'TO_BE_EXTENDED'
CIRCUIT_STATE_BROKEN = 'BROKEN'

MESSAGE_CREATE = chr(1)
MESSAGE_CREATED = chr(2)
MESSAGE_EXTEND = chr(3)
MESSAGE_EXTENDED = chr(4)
MESSAGE_DATA = chr(5)
MESSAGE_PING = chr(7)
MESSAGE_PONG = chr(8)
MESSAGE_PUNCTURE = chr(9)
MESSAGE_STATS = chr(10)

MESSAGE_STRING_REPRESENTATION = {
    MESSAGE_CREATE: u'create',
    MESSAGE_CREATED: u'created',
    MESSAGE_EXTEND: u'extend',
    MESSAGE_EXTENDED: u'extended',
    MESSAGE_DATA: u'data',
    MESSAGE_PING: u'ping',
    MESSAGE_PONG: u'pong',
    MESSAGE_PUNCTURE: u'puncture',
    MESSAGE_STATS: u'stats'
}

PING_INTERVAL = (CANDIDATE_WALK_LIFETIME - 5.0) / 4
