name: windows_dependencies
description: Setup windows dependencies for Tribler
inputs:
  libsodium-version:
    default: '1.0.18'
    description: 'Libsodium version'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Cache Binaries
      id: cache-binaries
      uses: actions/cache@v3
      with:
        path: cached-bin
        key: ${{ runner.os }}-cached-bin

    - name: Create bin folder
      shell: cmd
      run: |
        if not exist "cached-bin" mkdir "cached-bin"

    - name: Check Libsodium existence
      id: check_libsodium
      uses: andstor/file-existence-action@v2
      with:
        files: "cached-bin/libsodium-${{inputs.libsodium-version}}/libsodium.dll"

    - name: Download Libsodium
      if: steps.check_libsodium.outputs.files_exists == 'false'
      shell: pwsh
      run: |
        echo Downloading libsodium-${{inputs.libsodium-version}}-msvc.zip
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
        Invoke-WebRequest -Uri https://download.libsodium.org/libsodium/releases/libsodium-${{inputs.libsodium-version}}-msvc.zip -OutFile libsodium-${{inputs.libsodium-version}}-msvc.zip

        7z x libsodium-${{inputs.libsodium-version}}-msvc.zip

        $RELEASE_FOLDER = (Get-Location).Path + "\libsodium\x64\Release"
        $latest_release = Get-ChildItem -Path $RELEASE_FOLDER -Directory | Sort-Object CreationTime -Descending | Select-Object -First 1 -ExpandProperty Name

        $targetDir = ".\cached-bin\libsodium-${{inputs.libsodium-version}}"
        if (-not (Test-Path -Path $targetDir)) {
            New-Item -ItemType Directory -Path $targetDir
        }

        Copy-Item "$RELEASE_FOLDER\$latest_release\dynamic\libsodium.dll" -Destination "$targetDir\libsodium.dll"

    - name: Install Libsodium
      shell: cmd
      run: |
        copy .\cached-bin\libsodium-${{inputs.libsodium-version}}\libsodium.dll C:\Windows\system32\
