name: windows_dependencies
description: Setup windows dependencies for Tribler
inputs:
  libsodium-version:
    default: '1.0.18'
    description: 'Libsodium version'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Cache Binaries
      id: cache-binaries
      uses: actions/cache@v4
      with:
        path: cached-bin
        key: ${{ runner.os }}-cached-bin

    - name: Create bin folder
      shell: cmd
      run: |
        if not exist "cached-bin" mkdir "cached-bin"

    - name: Check Libsodium existence
      id: check_libsodium
      uses: andstor/file-existence-action@v3
      with:
        files: "cached-bin/libsodium-${{inputs.libsodium-version}}/libsodium.dll"

    - name: Download Libsodium
      if: steps.check_libsodium.outputs.files_exists == 'false'
      env:
        RELEASE_FOLDER: .\libsodium\x64\Release
      shell: cmd
      run: |
        curl -o libsodium.zip https://download.libsodium.org/libsodium/releases/libsodium-${{inputs.libsodium-version}}-msvc.zip
        7z x libsodium.zip
        dir %RELEASE_FOLDER% /ad /b /o-n > latest_release_file
        set /p latest_release= < latest_release_file
        echo Latest release: %latest_release%
        if not exist "cached-bin\libsodium-${{inputs.libsodium-version}}" mkdir "cached-bin\libsodium-${{inputs.libsodium-version}}"
        copy %RELEASE_FOLDER%\%latest_release%\dynamic\libsodium.dll .\cached-bin\libsodium-${{inputs.libsodium-version}}\libsodium.dll

    - name: Install Libsodium
      shell: cmd
      run: |
        copy .\cached-bin\libsodium-${{inputs.libsodium-version}}\libsodium.dll C:\Windows\system32\
