name: MacOS

on:
  workflow_call:
    inputs:
      os:
        default: macos-latest
        type: string
        required: false

      python-version:
        default: 3.8
        type: string
        required: false

      upload:
        default: false
        type: boolean
        required: false

      ref:
        default: ${{ github.ref }}
        type: string
        required: false

  workflow_dispatch:
    inputs:
      os:
        description: Environment
        default: macos-10.15
        type: string
        required: true

      python-version:
        description: Python version
        default: 3.8
        type: string
        required: true

      upload:
        description: Upload
        default: true
        type: boolean
        required: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ github.event.inputs.os || inputs.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{inputs.ref || github.ref}}

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ github.event.inputs.python-version || inputs.python-version }}

      - uses: ./.github/actions/save_git_info

      - name: Prepare files
        env:
          SENTRY_URL: ${{secrets.SENTRY_URL}}
        run: |
          python ./build/update_version.py -r .

      - name: Run build script
        timeout-minutes: 15
        env:
          QT_QPA_PLATFORM: offscreen
          QT_ACCESSIBILITY: 1
          QT_IM_MODULE: ibus
          LOG_LEVEL: INFO
        run: |
          ./build/mac/makedist_macos.sh

      - name: Upload Artifact
        if: github.event.inputs.upload || inputs.upload
        uses: actions/upload-artifact@v3
        with:
          name: tribler.dmg
          path: ./dist/Tribler-${{env.TRIBLER_VERSION}}.dmg
          retention-days: 1
